# Tutorial of Theano

Source: http://deeplearning.net/software/theano/tutorial/index.html

## Preparation
Import Theano packages and other necessary packages

In [1]:
from theano import *
import theano.tensor as T
import numpy as np

## Data type declaration

In Theano, all symbols must be typed.
In particular, `T.dscalar` is the type we assign to
“0-dimensional arrays (`scalar`) of doubles (`d`)”.
It is a Theano Type.

`dscalar` is not a class.
Therefore, neither `x` nor `y` are actually instances of `dscalar`.
They are instances of `TensorVariable`
assigned the Theano Type `dscalar` in their type field,
as shown here:

In [2]:
x = T.dscalar('x')
y = T.dscalar('y')
print(type(x))
print(x.type)
print(T.dscalar)
print(x.type is T.dscalar)

<class 'theano.tensor.var.TensorVariable'>
TensorType(float64, scalar)
TensorType(float64, scalar)
True


Theano uses expression to describe the relation between variables.
Now a new variable `z` is defined to be the summation of `x` and `y`.
Use Theano `pp` to pretty-print `z`.

In [3]:
z = x + y
pp(z)

'(x + y)'

Theano uses the keyword `function` to name such relationship.
The first argument to function is a list of variables served as function input.
The second argument is a single Variable or a list of Variables as function output.
`f` may then be used like a normal Python function.



In [4]:
f = function([x, y], z)
f(2,3)

array(5.)

## Extension to matrix data types

`dmatrix` is the Type for matrices of doubles.
Now we define our variables to be matrices.

In [5]:
x = T.dmatrix('x')
y = T.dmatrix('y')
print(type(x))
print(x.type)
print(T.dmatrix)
print(x.type is T.dmatrix)

<class 'theano.tensor.var.TensorVariable'>
TensorType(float64, matrix)
TensorType(float64, matrix)
True


In [6]:
z = x + y
f = function([x, y], z)

# addition of two vectors
f([[2,3]], [[4,5]])

array([[6., 8.]])

In [7]:
# addition of two matrices
f([[2,3],[4,5]], [[6,7],[8,9]])

array([[ 8., 10.],
       [12., 14.]])

It is also available to use `numpy` array data type as function input.

In [8]:
# addition of two numpy.array matrices
f(np.array([[2,3],[4,5]]), np.array([[6,7],[8,9]]))

array([[ 8., 10.],
       [12., 14.]])

Now we could also try other types such as `vector`.
The following function tries to compute $a^2 + b^2 + 2ab$.

In [9]:
a = T.vector()
b = T.vector()
out = a**2 + b**2 + 2*a*b
f = function([a, b], out)
f([0,1,2], [10,11,12])

array([100., 144., 196.])

## Logistic function

The following function computes the sigmoid.
$$s(x) = \frac{1}{1+e^{-x}}$$
Note that Theano has math library including `exp()`.

In [10]:
x = T.dmatrix()
s = 1/(1+T.exp(-x))
sigmoid = function([x], s)
sigmoid([[0, 1], [-1, -2]])

array([[0.5       , 0.73105858],
       [0.26894142, 0.11920292]])

## Function with multiple outputs

The following function computes summation, difference, and inner product of two vectors.

In [12]:
a = T.vector()
b = T.vector()
summ = a+b
diff = abs(a-b)
inpd = T.dot(a, b.T)
f = function([a, b], [summ, diff, inpd])
f([0,1,2], [10,11,12])

[array([10., 12., 14.]), array([10., 10., 10.]), array(35.)]